### ISSUE TITLE
The connection is lost if you change the file language

### ISSUE THREAD

**Issue by shixish** [jtokoph/ghosttext-vscode#1]
I'm able to get the it to connect and make changes, but if I try to switch the file language to javascript it disconnects the browser and editor.

**Comment by paulklemm** [comment]
I'm also experiencing this issue. Without this being fixed this package is of very little use.

**Comment by hryanjones** [comment]
I verified that [the fix](https://github.com/mazamachi/ghosttext-vscode/commit/a584d6c61975de9e215fafbbc96fa8e5217ab0ab) mentioned by @mazamachi works, but it looks like it hasn't been pulled into the main repository?
