### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by fregante** [jtokoph/ghosttext-vscode#11]
Hi Jason, I'm working on making this extension a first-party one, perhaps rewriting it from scratch. Would you be able to [pass](https://developercommunity.visualstudio.com/t/marketplace-allow-rename-of-publisher-name-id/617189#T-N629289) me the VS Code store publishing rights? This way I can send updates to existing users instead of manually pushing them to install a new extension.

**Comment by wormeyman** [comment]
Hey @fregante I personally switched to https://github.com/ctf0/ghosttext-vscode

**Comment by fregante** [comment]
Yeah, but [tokoph.ghosttext](https://marketplace.visualstudio.com/items?itemName=tokoph.ghosttext) has 4460 users so I'd like to keep updating that extension so everyone can get the updates.

**Comment by rollingmoai** [comment]
> Hey @fregante I personally switched to [ctf0/ghosttext-vscode](https://github.com/ctf0/ghosttext-vscode)

Even that is somehow dead now and the latest fork is https://github.com/ngyuki/vscode-ghosttext. Or this other repo https://github.com/samoylenkodmitry/vscodeghosttext

**Comment by rollingmoai** [comment]
So what's the plan now, no transfer?

**Comment by fregante** [comment]
Right now no plan, I have no time to work on it. If I do, I’ll just publish it under my name

**Comment by fregante** [comment]
The official version is now available: https://marketplace.visualstudio.com/items?itemName=fregante.ghost-text
