### ISSUE TITLE
Have to enable it every time?

### ISSUE THREAD

**Issue by GJRobert** [jtokoph/ghosttext-vscode#12]
Just installed this VS Code extension these couple of days.

Seems that I have to enable it in the Command Palette every time I started VS Code, otherwise Firefox cannot connect to GhostText in VS Code. Only me?

Environment:
- MacBook Air M1
- macOS Big Sur 11.6

**Comment by fregante** [comment]
You can now try the official version, which starts automatically: https://marketplace.visualstudio.com/items?itemName=fregante.ghost-text

**Comment by jd-solanki** [comment]
@fregante Just to let you know, Thanks so much for this, This is really useful ❤️
