### ISSUE TITLE
Official extension now available

### ISSUE THREAD

**Issue by fregante** [jtokoph/ghosttext-vscode#13]
Hello, I finally published the official extension for VS Code:

- https://github.com/fregante/GhostText-for-VSCode
- https://marketplace.visualstudio.com/items?itemName=fregante.ghost-text

I invite you to test it out, report any issues you see and contribute, if you have time. This is meant to replace the 3 forks currently available on the marketplace with a single, maintained, official version.

**Comment by jtokoph** [comment]
I've left a comment here to deprecate this extension in favor of the new one: https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-5609246

I'll also archive this repository.
