### ISSUE TITLE
Set a default file language

### ISSUE THREAD

**Issue by iherman** [jtokoph/ghosttext-vscode#3]
This is related to #1. At present, the file language is set to .txt by default (and, per #1, it is essentially impossible to change that, because the change would result in the change of the temporary file suffix). At the minimum, it should be possible to set the default file language via the settings.

**Comment by wormeyman** [comment]
@iherman I fixed it with

`        "files.associations": {
        "*.tmp": "html"
    },
`

in my settings config for vscode.

**Comment by wormeyman** [comment]
```js
    if (this.editor === null) {
      this.editorTitle = request.title;
      tmp.file({
        postfix: '.html'
      }, (err, path, fd, cleanupCallback) => {
        console.log("File: ", path);
        console.log("Filedescriptor: ", fd);
        this.cleanupCallback = cleanupCallback;
```

also works.

**Comment by fregante** [comment]
This is now possible in the official extension https://github.com/jtokoph/ghosttext-vscode/issues/13

<img width="504" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/226318020-2ffac866-4f3c-46a5-8336-3ad5763d8519.png">
