### ISSUE TITLE
Not working correctly in codemirror

### ISSUE THREAD

**Issue by pabli24** [jtokoph/ghosttext-vscode#5]
What am using:
- Windows 10 64bit
- Google chrome 64
- GhostText 17.12.11.910
- Visual Studio Code 1.20.1

Video showing the problem: https://www.youtube.com/watch?v=De89RVKLXFE&feature=youtu.be
Also when I want to change language of writing code, extension disconnects.

**Comment by fregante** [comment]
A new GhostText version for the browser has been released. I can't replicate this issue anymore
