### ISSUE TITLE
feature request - option so set a different extension (.md instead of .tmp)

### ISSUE THREAD

**Issue by aisbergde** [jtokoph/ghosttext-vscode#9]
I want to use the markdown preview feature of the "Markdown all in one" plugin, but it looks that the preview is only working in files with the file extension .md
It would be fine to find a way to use GhostText for MarkDown content together with Markdown preview. For example by an option to change the default extension from ".tmp" to ".md"

I will also try to use the plugin with extension .tmp, Maybe I can find a way.

**Comment by aisbergde** [comment]
in VS Code it is possible to configure file extensions
settings.json

```
    "files.associations": {
        "*.tmp": "markdown"
    },
```

**Comment by fregante** [comment]
Thank you for posting that here!

**Comment by fregante** [comment]
This is now possible in the official extension https://github.com/jtokoph/ghosttext-vscode/issues/13 both manual and automatic selection.

<img width="504" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/226318020-2ffac866-4f3c-46a5-8336-3ad5763d8519.png">
